import sys
sys.stdout.reconfigure(encoding='utf-8')

from sqlalchemy import text
from app.database import SessionLocal
from app.models.product import Product

db = SessionLocal()

products = db.query(Product).filter(Product.id.between(4, 103)).all()
target_asins = [p.asin for p in products if p.asin]

rows = db.execute(
    text("SELECT sku_id, product_name, final_product_title, all_keywords FROM final_product_data WHERE sku_id IN :asins"),
    {"asins": tuple(target_asins)}
).fetchall()

total_uploaded = len(target_asins)
total_saved = len(rows)
groq_generated = 0
fallback_generated = 0
failed = total_uploaded - total_saved

for r in rows:
    title = r[2] or ""
    if " | " in title:
        fallback_generated += 1
    else:
        groq_generated += 1

print("==========================================================================")
print("FINAL AUDIT REPORT FOR UPLOADED BATCH (1-100 PRODUCTS / IDs 4-103)")
print("==========================================================================")
print(f"1. Total Uploaded Batch Products      : {total_uploaded}")
print(f"2. Successfully Saved Records in DB  : {total_saved}")
print(f"3. Successfully Generated by Groq AI  : {groq_generated}")
print(f"4. Fallback Generated Count          : {fallback_generated}")
print(f"5. Failed Count                      : {failed}")
print("==========================================================================")

# Verify single product Requirement 10 detail
t2_rec = db.execute(text("SELECT product_name, sku_id, final_product_title, all_keywords FROM final_product_data WHERE sku_id = 'T2YVIVA000017'")).fetchone()
print("\nRequirement 10 Single Product Verification ('T2YVIVA000017'):")
print(f"  product_name       : {t2_rec[0]}")
print(f"  sku_id             : {t2_rec[1]}")
print(f"  final_product_title: {t2_rec[2]}")
print(f"  all_keywords (JSON): {t2_rec[3]}")

db.close()
