import sys
sys.stdout.reconfigure(encoding='utf-8')

from sqlalchemy import text
from app.database import SessionLocal
from app.models.product import Product
from app.services.title_generator import fallback_generate_title, clean_input_text

db = SessionLocal()

products = db.query(Product).filter(Product.id.between(4, 103)).all()
target_asins = [p.asin for p in products if p.asin]

rows = db.execute(
    text("SELECT sku_id, product_name, final_product_title, all_keywords FROM final_product_data WHERE sku_id IN :asins"),
    {"asins": tuple(target_asins)}
).fetchall()

exact_fallback_count = 0
groq_ai_count = 0

for r in rows:
    sku_id, p_name, final_title, kws_json = r[0], r[1], r[2], r[3]
    import json
    kws = json.loads(kws_json) if isinstance(kws_json, str) else (kws_json or [])
    expected_fallback = fallback_generate_title(p_name, kws)
    
    if final_title == expected_fallback:
        exact_fallback_count += 1
        print(f"Fallback matched: {sku_id} -> {final_title}")
    else:
        groq_ai_count += 1

print("==========================================================================")
print("EXACT DISAMBIGUATED TITLE GENERATION METRICS")
print("==========================================================================")
print(f"Total Target Batch Products (1-100) : {len(target_asins)}")
print(f"Successfully Generated by Groq AI  : {groq_ai_count}")
print(f"Fallback Generated Count          : {exact_fallback_count}")
print(f"Failed Count                      : {len(target_asins) - len(rows)}")
print("==========================================================================")

db.close()
